# Django settings for swarming_heads project.

import logging
import os

# Keep all references relative to this file
SITE_ROOT = os.path.realpath(os.path.dirname(__file__))

DEBUG = True
TEMPLATE_DEBUG = DEBUG

LOG_LEVEL = logging.DEBUG
LOG_FILE = 'swarming_heads.log'

RPC_SERVER_HOST = '127.0.0.1'
RPC_SERVER_PORT = 8045

STOMP_HOST = '127.0.0.1'
STOMP_PORT = 61613

ORBITED_HOST = '127.0.0.1'
ORBITED_PORT = 9000

ORBITED_CONFIG_FILE = os.path.join(SITE_ROOT, 'orbited.cfg')

# May not be needed?
ADMINS = (
    # ('Your Name', 'your_email@example.com'),
)

MANAGERS = ADMINS

# Point to urls.py to handle our url configuration
ROOT_URLCONF = 'swarming_heads.urls'

# We are using an sqlite3 database
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(SITE_ROOT, 'db/database.db'),
        'USER': '',                      
        'PASSWORD': '',                  
        'HOST': '',                      
        'PORT': '',                      
    }
}

# Local time zone for this installation. Choices can be found here:
# http://en.wikipedia.org/wiki/List_of_tz_zones_by_name
TIME_ZONE = 'Australia/Sydney'

# Language code for this installation. All choices can be found here:
# http://www.i18nguy.com/unicode/language-identifiers.html
LANGUAGE_CODE = 'en-us'

SITE_ID = 1

# If you set this to False, Django will make some optimizations so as not
# to load the internationalization machinery.
USE_I18N = True

# If you set this to False, Django will not format dates, numbers and
# calendars according to the current locale
USE_L10N = True


STATIC_ROOT = os.path.join(SITE_ROOT, 'static')

# URL prefix for static files.
STATIC_URL = '/static/'    

# Absolute filesystem path to the directory that will hold user-uploaded files.
MEDIA_ROOT = os.path.join(SITE_ROOT, 'media')

# We want media to be stored as static files
MEDIA_URL = '/media/'

# URL prefix for admin static files -- CSS, JavaScript and images.
ADMIN_MEDIA_PREFIX = '/static/admin/'

# List of directories to search for static files
STATICFILES_DIRS = (    MEDIA_ROOT,
)

# List of finder classes that know how to find static files in various locations.
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

SECRET_KEY = '+i%4%7_9u(j*1)o*zroago98np-z1z81##$1^2*@eu01ckl183'

# List of callables that know how to import templates from various sources.
TEMPLATE_LOADERS = (
    'django.template.loaders.filesystem.Loader',
    'django.template.loaders.app_directories.Loader',
)

MIDDLEWARE_CLASSES = (
    'django.middleware.common.CommonMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
)

# List of directories to search for templatel
TEMPLATE_DIRS = (
    os.path.join(SITE_ROOT, 'templates')             
)

# List of 'Applications' 
INSTALLED_APPS = (
    'django.contrib.auth',
    'django.contrib.humanize',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.sites',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.admin',
    'django.contrib.admindocs',
    'apps.testing'
)

# A sample log configuration.
# This was generated by Django, and will need to change
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'mail_admins': {
            'level': 'ERROR',
            'class': 'django.utils.log.AdminEmailHandler'
        }
    },
    'loggers': {
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
    }
}
